name: varicon_form_builder
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  cached_network_image: ^3.4.1
  collection: ^1.19.0
  dotted_line: ^3.2.3
  expandable: ^5.0.1
  file_picker: ^8.3.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.7.0
  flutter_riverpod: ^2.6.1
  flutter_widget_from_html_core: ^0.15.2
  fluttertoast: ^8.2.12
  form_builder_validators: ^11.1.1
  freezed_annotation: ^2.2.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  hooks_riverpod: ^2.6.1
  html_editor_enhanced: ^2.6.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.5
  riverpod: ^2.6.1
  signature: ^5.5.0
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.4.0
  build_runner: ^2.4.15
  json_serializable: ^6.7.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  assets:
    - assets/
    - assets/image/
  # To add assets to your package, add an assets section, like this:
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
