name: varicon_form_builder
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  intl: ^0.18.0
  file_picker: ^5.3.2
  image_picker: ^1.0.1
  permission_handler: ^11.2.0
  downloads_path_provider_28: ^0.1.2
  path_provider: ^2.0.15
  flutter_image_compress: ^2.0.3
  fluttertoast: ^8.2.2 
  flutter_signature_pad: ^3.0.1
  flutter_animate: ^4.2.0+1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  dotted_line: ^3.2.2
  dotted_border: ^2.1.0
  intl_phone_field: ^3.2.0
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  assets:
    - assets/
    - assets/image/
  fonts:
    - family: Roboto_Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto_Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Roboto_Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto_Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
